# -*- coding: utf-8 -*-
"""tugas 9 alpro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtjDDDXMDGKpJf8jQUTaJNxubLWx3w7e

Diberikan list berikut:
buah = ['apel', 'mangga', 'jeruk', 'anggur', 'pisang']

*   Tambahkan 'semangka' di akhir list
*   Sisipkan 'durian' di antara 'jeruk' dan 'anggur'
*   Hapus 'mangga' dari list
*   Ubah 'pisang' menjadi 'nanas'
*   Tampilkan 3 buah pertama



2. Diberikan list berikut:
angka = [45, 12, 78, 23, 56, 89, 34]
* Urutkan list secara ascending
* Urutkan list secara descending
"""

buah = ['apel', 'mangga', 'jeruk', 'anggur', 'pisang']
print(f"List buah semula:\t{buah}")

#tambah semangka
buah.append('semangka')
print(f"List buah setelah ditambahkan:\t{buah}\t")

#sisipkan durian diantara jeruk dan angguur
buah.insert(3, 'durian')
print(f"data setelah disisipkan buah baru:\t{buah}")

#hapus mangga dari list
buah.remove('mangga')
print(f"list buah setelah dihapus:\t{buah}")

# ubah pisang ke nanas
print('\nubah buah pisang ke nanas')
print(f"buah sekarang:\t{buah[-2]}")
buah[-2]= 'nanas'
print(f"buah setelah diganti:\t{buah[-2]}")

#tampilkan 3 buah pertama
print("\nlist 3 buah pertama")
print(f'buah 1:\t{buah[0]}')
print(f'buah 2:\t{buah[1]}')
print(f'buah 3:\t{buah[2]}')

print('\npakai cara lain')
print(buah[0:3])

"""
2. Diberikan list berikut:
angka = [45, 12, 78, 23, 56, 89, 34]
a. Urutkan list secara ascending
b. Urutkan list secara descending"""

angka = [45, 12, 78, 23, 56, 89, 34]
print(f"data sebelum: {angka}")

angka.sort()
print(f"data diurutkan{angka}")

angka.reverse()
print(f"data descending{angka}")