# -*- coding: utf-8 -*-
"""tugas 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKwfNGtAiudvELPOVe2xn0BjTnDkLb7r

TUGAS NO 1 (TUPLES)
"""

data_m1 = ("Radja Harismansyah",2505060076, "Teknologi Informasi")
data_m2 =("Huddin", 2505060076, "Teknologi Informasi")
data_m3 =("Gavin", 2505060073, "Teknologi Informasi")

data_mahasiswa_keseluruhan= (data_m1)
print(f"berikut data mahasiswa ke 1: {data_mahasiswa_keseluruhan}")
print(f"Hanya Nama: {data_mahasiswa_keseluruhan[0]}")
print(f"Hanya NIM: {data_mahasiswa_keseluruhan[1]}")
print(f"Hanya Prodi: {data_mahasiswa_keseluruhan[2]}")

"""TUGAS NO 2 (DICTIONARY)"""

keranjang = {
    "apel": 5000,
    "pisang": 3000,
    "jeruk": 7000,
    "anggur": 15000

}
perulangan = 0
total = 0
for buah, harga in keranjang.items():
  print(f"Harga {buah}: Rp {harga}")
  total += harga
print(f"\ntotal harga: {total}")