# -*- coding: utf-8 -*-
"""TUGAS 11 R

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSUTaY33YHG1WyGg3NoGaHKUyWSymjym

Latihan
Buatlah program sistem manajemen perpustakaan sederhana (menambahkan dan
menampilkan buku baru ke dalam sistem) menggunakan konsep multi-keys dan nesting
dictionary dengan format
- KEYS
- JUDUL BUKU
- PENULIS
- TAHUN TERBIT
- TANGGAL TERAKHIR PINJAM
- STATUS (TERSEDIA / TIDAK)
"""

import datetime
import random
import string

# lemari sebagai database
lemari = {}

print("SELAMAT DATANG DI DASHBOARD")

while True:
    print("Silahkan tambah buku baru")
    buku_baru = {}

    # perbarui buku_baru
    buku_baru["judul"] = input("Masukkan judul buku: ")
    buku_baru["penulis"] = input("Masukkan penulis buku: ")
    buku_baru["tahun_terbit"] = input("Masukkan tahun terbit buku: ")

    #terakhir dipinjam
    tahun = int(input("Masukkan tahun terakhir dipinjam (YYYY): "))
    bulan = int(input("Masukkan bulan terakhir dipinjam (1-12): "))
    tanggal = int(input("Masukkan tanggal terakhir dipinjam (1-31): "))
    buku_baru["tanggal_terakhir_dipinjam"] = datetime.datetime(tahun, bulan, tanggal)

    #status ketersediaan
    dipinjam = input("Apakah buku tersedia? (y/n): ").lower()
    if dipinjam == "y":
        buku_baru["status"] = True
    else:
        buku_baru["status"] = False

    #buat key acak
    key = "".join([random.choice(string.ascii_uppercase) for i in range(6)])

    #tambahin ke lemari
    lemari[key] = buku_baru
    print("\nBuku berhasil ditambahkan kunci: ", key)

    #tampilkan lemari
    print("\nDaftar Buku di Lemari:\n")
    print(f"{'KODE':<8} {'JUDUL':<25} {'PENULIS':<20} {'TAHUN TERBIT':<14} {'TERAKHIR DIPINJAM':<18} {'STATUS':<15}")
    print("-" * 150)
    for kode, data in lemari.items():
        terakhir_dipinjam = data['tanggal_terakhir_dipinjam'].strftime("%Y-%m-%d")
        status = "Tersedia" if data['status'] else "Tidak"
        print(f"{kode:<8} {data['judul']:<25} {data['penulis']:<20} {data['tahun_terbit']:<14} {terakhir_dipinjam:<18} {status:<15}")

    #tambah buku
    lagi = input("\nMau tambah buku lagi? (y/n): ").lower()
    if lagi != "y":
        print("Terima kasih, silahkan datang kembali!")
        break