# -*- coding: utf-8 -*-
"""Tugas 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgvh0gnMAUraD_2I83zH1Qp_-AxoWYQk
"""

#Luas persegi panjang
def luas_persegi_panjang(panjang, lebar):
  luas= panjang*lebar
  return luas

panjang = int(input("Masukkan panjang: " ))
lebar = int(input("Masukkan lebar: " ))
luas = panjang*lebar

luas_persegi_panjang(panjang, lebar)


#volume balok
# def volume_balok(panjang, lebar, tinggi):

# volume balok
print('cara 1)')
def volume_balok(panjang, lebar, tinggi):
  volume= panjang* lebar * tinggi
  return volume

panjang = int(input("Masukkan panjang: " ))
lebar = int(input("Masukkan lebar: " ))
tinggi = int(input("Masukkan tinggi: " ))

print(volume_balok(panjang, lebar, tinggi))


#cara 2
print('cara 2')
def volume_balok():
  panjang = int(input("Masukkan panjang: " ))
  lebar = int(input("Masukkan lebar: " ))
  tinggi = int(input("Masukkan tinggi: " ))

  return panjang* lebar *tinggi
print(volume_balok())

#menghitung luas jari2
def luas_lingkaran():
    print("Menghitung luas lingkaran")

    jari_jari = int(input("Jari-jari\t:"))
    return 3.14 * jari_jari**2

print(luas_lingkaran())

# menghitung volume bola
def volume_bola():
    print("Menghitung volume bola")

    jari_jari = int(input("Jari-jari\t:"))
    return .75 * 3.14 * jari_jari**3

print(volume_bola())